version: "3.8"

networks:
  apimvc:

services:
  TrocaTrocaDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apimvc-database
    ports:
      - "1433:1433"
    volumes:
      - ./database-apimvc:/db/database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin@1234
    networks:
      - apimvc